### PR TITLE
add bash to docker container

### PR DESCRIPTION
**Pull request by czue**
see https://github.com/unicef/etools-issues/issues/592

### CODE REVIEW

**Comment by czue** [comment]
I don't think the build failure is related though not sure what I should do to try and fix it...
`ECONFLICT Unable to find suitable version for paper-dialog`

**Comment by ewheeler** [comment]
@czue i believe that is `bower update`getting confused about which version of paper-dialog to use

screen shot 2017-08-10 at 15 42 19

@robertavram @marko911 would it be safe to change the frontend apps to specify 2.0.0 instead of 1.1.0? (presumably in `bower.json`?)

**Comment by robertavram** [comment]
i say it would need to be tested properly. Someone needs to dig into the t2f paper-dialog usage and confirm that it can be upgraded @marko911 @adi130987

**Comment by marko911** [comment]
@ewheeler I've changed it to 2.0.0 in my latest PR on Dashboard, but would have to  test it in t2f to see if anything breaks with the newer version as @robertavram suggests....

**Pull request closed without merging**
